IRn <- read.csv(file="./insertionsort_random.csv", header=FALSE, sep=",")
IRe <- read.csv(file="./insertionsort_reverse.csv", header=FALSE, sep=",") 
ISo <- read.csv(file="./insertionsort_sorted.csv", header=FALSE, sep=",")
MRn <- read.csv(file="./mergesort_random.csv", header=FALSE, sep=",")
MRe <- read.csv(file="./mergesort_reverse.csv", header=FALSE, sep=",") 
MSo <- read.csv(file="./mergesort_sorted.csv", header=FALSE, sep=",")
HRn <- read.csv(file="./heapsort_random.csv", header=FALSE, sep=",")
HRe <- read.csv(file="./heapsort_reverse.csv", header=FALSE, sep=",") 
HSo <- read.csv(file="./heapsort_sorted.csv", header=FALSE, sep=",")
SRn <- read.csv(file="./sortutility_random.csv", header=FALSE, sep=",")
SRe <- read.csv(file="./sortutility_reverse.csv", header=FALSE, sep=",") 
SSo <- read.csv(file="./sortutility_sorted.csv", header=FALSE, sep=",")
# random input runtime
plot( data.matrix(IRn[1]), data.matrix(IRn[2]), type="l", col="blue", xlab = "Input Size", ylab= "Run Time",main = "Plot for Runtime on Random Input")
lines(data.matrix(IRn[1]), data.matrix(MRn[2]), col="green")
lines(data.matrix(IRn[1]), data.matrix(HRn[2]), col="red")
lines(data.matrix(IRn[1]), data.matrix(SRn[2]), col="orange")
a <- max(data.matrix(IRn[2]),data.matrix(MRn[2]),data.matrix(HRn[2]),data.matrix(SRn[2]))
b <- min(data.matrix(IRn[1]))
legend(b, a, legend=c("Insertion sort", "Merge sort","Heap sort","Sort utility"),col=c("blue", "green","red","orange"), lty=1:1, cex=0.8)
# random input comparisons
plot( data.matrix(IRn[1]), data.matrix(IRn[3]), type="l", col="blue", xlab = "Input Size", ylab= "Run Time",main = "Plot for Comparisons on Random Input")
lines(data.matrix(IRn[1]), data.matrix(MRn[3]), col="green")
lines(data.matrix(IRn[1]), data.matrix(HRn[3]), col="red")
lines(data.matrix(IRn[1]), data.matrix(SRn[3]), col="orange")
a <- max(data.matrix(IRn[3]),data.matrix(MRn[3]),data.matrix(HRn[3]),data.matrix(SRn[3]))
b <- min(data.matrix(IRn[1]))
legend(b, a, legend=c("Insertion sort", "Merge sort","Heap sort","Sort utility"),col=c("blue", "green","red","orange"), lty=1:1, cex=0.8)
# sorted input runtime
plot( data.matrix(ISo[1]), data.matrix(ISo[2]), type="l", col="blue", xlab = "Input Size", ylab= "Run Time",main = "Plot for Runtime on Sorted Input")
lines(data.matrix(ISo[1]), data.matrix(MSo[2]), col="green")
lines(data.matrix(ISo[1]), data.matrix(HSo[2]), col="red")
lines(data.matrix(ISo[1]), data.matrix(SSo[2]), col="orange")
a <- max(data.matrix(ISo[2]),data.matrix(MSo[2]),data.matrix(HSo[2]),data.matrix(SSo[2]))
b <- min(data.matrix(ISo[1]))
legend(b, a, legend=c("Insertion sort", "Merge sort","Heap sort","Sort utility"),col=c("blue", "green","red","orange"), lty=1:1, cex=0.8)
# sorted input comparisons
plot( data.matrix(ISo[1]), data.matrix(ISo[3]), type="l", col="blue", xlab = "Input Size", ylab= "Run Time",main = "Plot for Comparisons on Sorted Input")
lines(data.matrix(ISo[1]), data.matrix(MSo[3]), col="green")
lines(data.matrix(ISo[1]), data.matrix(HSo[3]), col="red")
lines(data.matrix(ISo[1]), data.matrix(SSo[3]), col="orange")
a <- max(data.matrix(ISo[3]),data.matrix(MSo[3]),data.matrix(HSo[3]),data.matrix(SSo[3]))
b <- min(data.matrix(ISo[1]))
legend(b, a, legend=c("Insertion sort", "Merge sort","Heap sort","Sort utility"),col=c("blue", "green","red","orange"), lty=1:1, cex=0.8)
# reverse input runtime
plot( data.matrix(IRe[1]), data.matrix(IRe[2]), type="l", col="blue", xlab = "Input Size", ylab= "Run Time",main = "Plot for Runtime on Reverse Input")
lines(data.matrix(IRe[1]), data.matrix(MRe[2]), col="green")
lines(data.matrix(IRe[1]), data.matrix(HRe[2]), col="red")
lines(data.matrix(IRe[1]), data.matrix(SRe[2]), col="orange")
a <- max(data.matrix(IRe[2]),data.matrix(MRe[2]),data.matrix(HRe[2]),data.matrix(SRe[2]))
b <- min(data.matrix(IRe[1]))
legend(b, a, legend=c("Insertion sort", "Merge sort","Heap sort","Sort utility"),col=c("blue", "green","red","orange"), lty=1:1, cex=0.8)
# reverse input comparisons
plot( data.matrix(IRe[1]), data.matrix(IRe[3]), type="l", col="blue", xlab = "Input Size", ylab= "Run Time",main = "Plot for Comparisons on Reverse Input")
lines(data.matrix(IRe[1]), data.matrix(MRe[3]), col="green")
lines(data.matrix(IRe[1]), data.matrix(HRe[3]), col="red")
lines(data.matrix(IRe[1]), data.matrix(SRe[3]), col="orange")
a <- max(data.matrix(IRe[3]),data.matrix(MRe[3]),data.matrix(HRe[3]),data.matrix(SRe[3]))
b <- min(data.matrix(IRe[1]))
legend(b, a, legend=c("Insertion sort", "Merge sort","Heap sort","Sort utility"),col=c("blue", "green","red","orange"), lty=1:1, cex=0.8)

